version = 1

[[annotations]]
path = [
  "emacs*/**",
  "dbus-broker/**",
  "amberol/**",
]
SPDX-FileCopyrightText = "NOASSERTION"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "mutter/**"
SPDX-FileCopyrightText = "NOASSERTION"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = [
  "gnomeExtensions/tiling-assistant/**",
  "wireshark/**",
]
SPDX-FileCopyrightText = "NOASSERTION"
SPDX-License-Identifier = "GPL-2.0-only"
