#!/usr/bin/env bash
# Copyright (C) Archit Gupta <archit@accelbread.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

set -euo pipefail

if [ -f flake.nix ]; then
  TREE=$(mktemp -d)
  trap 'rm -rf -- "$TREE"' EXIT
  cp -r .git "$TREE/"
  cd "$TREE"
  rm -f .git/index.lock || true
  git restore .
  git submodule update --init --recursive --checkout --no-fetch
  nix flake check --offline "$TREE"
fi
