[formatter.zig]
command = "zig"
options = ["fmt"]
includes = ["*.zig"]

[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.md"]
