;;; adwaita-theme.el --- Custom theme -*- lexical-binding: t; -*-

;;; Commentary:

;; Theme based off of Adwaita colors

;;; Code:

(deftheme adwaita)

(let* ((accent-blue "#3584e4")
       (accent-teal "#2190a4")
       (accent-green "#3a944a")
       (accent-yellow "#c88800")
       (accent-orange "#ed5b00")
       (accent-red "#e62d42")
       (accent-pink "#d56199")
       (accent-purple "#9141ac")
       (accent-slate "#6f8396")
       (accent-bg-color accent-purple)
       (accent-fg-color "#ffffff")
       (accent-color "#fba7ff")
       (destructive-bg-color "#c01c28")
       (destructive-fg-color "#ffffff")
       (destructive-color "#ff938c")
       (success-bg-color "#26a269")
       (success-fg-color "#ffffff")
       (success-color "#78e9ab")
       (warning-bg-color "#cd9309")
       (warning-fg-color "#291d02")
       (warning-color "#ffc252")
       (error-bg-color "#c01c28")
       (error-fg-color "#ffffff")
       (error-color "#ff938c")
       (window-bg-color "#222226")
       (window-fg-color "#ffffff")
       (view-bg-color "#1d1d20")
       (view-fg-color "#ffffff")
       (headerbar-bg-color "#2e2e32")
       (headerbar-fg-color "#ffffff")
       (sidebar-bg-color "#2e2e32")
       (sidebar-fg-color "#ffffff")
       (secondary-sidebar-bg-color "#28282c")
       (sidebar-fg-color "#ffffff")
       (blue-1 "#99c1f1")
       (blue-2 "#62a0ea")
       (blue-3 "#3584e4")
       (blue-4 "#1c71d8")
       (blue-5 "#1a5fb4")
       (green-1 "#8ff0a4")
       (green-2 "#57e389")
       (green-3 "#33d17a")
       (green-4 "#2ec27e")
       (green-5 "#26a269")
       (yellow-1 "#f9f06b")
       (yellow-2 "#f8e45c")
       (yellow-3 "#f6d32d")
       (yellow-4 "#f5c211")
       (yellow-5 "#e5a50a")
       (orange-1 "#ffbe6f")
       (orange-2 "#ffa348")
       (orange-3 "#ff7800")
       (orange-4 "#e66100")
       (orange-5 "#c64600")
       (red-1 "#f66151")
       (red-2 "#ed333b")
       (red-3 "#e01b24")
       (red-4 "#c01c28")
       (red-5 "#a51d2d")
       (purple-1 "#dc8add")
       (purple-2 "#c061cb")
       (purple-3 "#9141ac")
       (purple-4 "#813d9c")
       (purple-5 "#613583")
       (brown-1 "#cdab8f")
       (brown-2 "#b5835a")
       (brown-3 "#986a44")
       (brown-4 "#865e3c")
       (brown-5 "#63452c")
       (light-1 "#ffffff")
       (light-2 "#f6f5f4")
       (light-3 "#deddda")
       (light-4 "#c0bfbc")
       (light-5 "#9a9996")
       (dark-1 "#77767b")
       (dark-2 "#5e5c64")
       (dark-3 "#3d3846")
       (dark-4 "#241f31")
       (dark-5 "#000000"))
  (custom-theme-set-faces
   'adwaita
   `(default ((t (:background ,view-bg-color :foreground ,view-fg-color))))
   '(variable-pitch-text ((t (:inherit (variable-pitch)))))
   `(cursor ((t (:background ,view-fg-color))))
   `(homoglyph ((t (:foreground ,warning-bg-color :inherit (bold)))))
   '(escape-glyph ((t (:inherit (homoglyph)))))
   `(minibuffer-prompt ((t (:foreground ,accent-color))))
   '(highlight ((t (:background "#3b3b3d"))))
   `(region ((t (:extend nil :background ,purple-5))))
   `(shadow ((t (:foreground ,dark-1))))
   `(warning ((t (:weight bold :foreground ,warning-color))))
   `(success ((t (:weight bold :foreground ,success-color))))
   `(error ((t (:weight bold :foreground ,error-color))))
   `(secondary-selection ((t (:extend nil :background ,dark-3))))
   `(trailing-whitespace ((t (:background ,dark-3))))
   `(font-lock-builtin-face ((t (:foreground ,yellow-1))))
   '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
   `(font-lock-comment-face ((t (:foreground ,light-5 :extend t))))
   `(font-lock-constant-face ((t (:foreground ,orange-1))))
   `(font-lock-doc-face ((t (:foreground ,blue-1 :extend t))))
   `(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
   `(font-lock-function-name-face ((t (:foreground ,blue-3))))
   `(font-lock-keyword-face ((t (:foreground ,purple-2))))
   '(font-lock-negation-char-face ((t (:inherit (homoglyph)))))
   `(font-lock-preprocessor-face ((t (:foreground ,brown-3 :inherit (bold)))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,orange-1))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,orange-1))))
   `(font-lock-string-face ((t (:foreground ,green-2))))
   `(font-lock-type-face ((t (:foreground ,purple-1))))
   `(font-lock-variable-name-face ((t (:foreground ,brown-1))))
   '(font-lock-warning-face ((t (:inherit (warning)))))
   '(button ((t (:inherit (link)))))
   `(link ((t (:weight bold :underline (:color foreground-color :style line)
                       :foreground ,accent-color))))
   `(link-visited ((t (:foreground ,accent-color))))
   `(fringe ((t (:foreground ,accent-bg-color))))
   '(header-line ((t (:inherit (mode-line)))))
   `(mode-line ((t (:box (:line-width (8 . 4) :color ,headerbar-bg-color
                                      :style nil)
                         :background ,headerbar-bg-color
                         :foreground ,headerbar-fg-color
                         :inherit (variable-pitch)))))
   `(mode-line-flash ((t (:background ,headerbar-fg-color
                                      :foreground ,headerbar-bg-color
                                      :inherit (mode-line)))))
   '(mode-line-inactive ((t (:box (:line-width (8 . 4) :color "#28282C"
                                               :style nil)
                                  :background "#28282C"
                                  :foreground "#939395"
                                  :inherit (mode-line)))))
   '(mode-line-buffer-id ((t (:weight bold))))
   `(mode-line-emphasis ((t (:foreground ,accent-color))))
   '(mode-line-highlight ((t (:inherit (highlight)))))
   '(eglot-mode-line ((t (:inherit (fringe)))))
   '(tab-bar ((t (:inherit (mode-line)))))
   '(tab-bar-tab ((t (:inherit (mode-line)))))
   '(tab-bar-tab-inactive ((t (:inherit (mode-line-inactive)))))
   '(window-divider ((t (:foreground "#28282C"))))
   '(window-divider-first-pixel ((t (:inherit (window-divider)))))
   '(window-divider-last-pixel ((t (:inherit (window-divider)))))
   '(transient-key-exit ((t (:inherit (font-lock-function-name-face)))))
   '(transient-key-stay ((t (:inherit (font-lock-variable-name-face)))))
   '(transient-key-return ((t (:inherit (font-lock-warning-face)))))
   '(isearch ((t (:weight bold :inherit (lazy-highlight)))))
   `(isearch-fail ((t (:weight bold :foreground ,error-fg-color :background ,error-bg-color))))
   '(lazy-highlight ((t (:inherit secondary-selection))))
   '(next-error ((t (:inherit (region)))))
   '(query-replace ((t (:inherit (isearch)))))
   '(whitespace-tab ((t (:inherit (shadow)))))
   '(whitespace-trailing ((t (:inherit (secondary-selection)))))
   '(whitespace-missing-newline-at-eof ((t (:inherit (isearch-fail)))))
   '(page-break-lines ((t (:inherit (shadow)))))
   '(vundo-highlight ((t (:inherit (minibuffer-prompt)))))
   `(jinx-misspelled ((t (:underline (:style wave :color ,error-bg-color)))))
   '(jinx-save ((t (:inherit (font-lock-builtin-face)))))
   '(evil-ex-info ((t (:inherit (minibuffer-prompt)))))
   '(evil-ex-substitute-matches ((t (:strike-through t :inherit (error)))))
   '(evil-ex-substitute-replacement ((t (:inherit (success)))))
   '(evil-ex-info ((t (:inherit (minibuffer-prompt)))))
   `(Man-overstrike ((t (:foreground ,accent-bg-color :inherit (bold fixed-pitch)))))
   `(Man-underline ((t (:foreground ,accent-color :inherit (italic fixed-pitch)))))
   '(woman-bold ((t (:inherit (Man-overstrike)))))
   '(woman-italic ((t (:inherit (Man-underline)))))
   '(rainbow-delimiters-depth-1-face ((t (:foreground "#BF7FFF"))))
   '(rainbow-delimiters-depth-2-face ((t (:foreground "#7FBFFF"))))
   '(rainbow-delimiters-depth-3-face ((t (:foreground "#7FFFBF"))))
   '(rainbow-delimiters-depth-4-face ((t (:foreground "#BFFF7F"))))
   '(rainbow-delimiters-depth-5-face ((t (:foreground "#FFBF7F"))))
   '(rainbow-delimiters-depth-6-face ((t (:foreground "#FF7FBF"))))
   `(rainbow-delimiters-base-error-face ((t (:foreground ,error-bg-color))))
   '(dired-broken-symlink ((t (:inherit (error)))))
   `(dired-directory ((t (:foreground ,blue-2))))
   '(dired-flagged ((t (:strike-through t :inherit (error)))))
   `(dired-header ((t (:foreground ,accent-bg-color))))
   `(dired-mark ((t (:foreground ,accent-bg-color))))
   `(dired-marked ((t (:weight bold :foreground ,purple-1))))
   `(dired-perm-write ((t (:foreground ,red-1))))
   `(dired-special ((t (:foreground ,orange-1))))
   `(dired-symlink ((t (:foreground ,green-1))))
   '(eshell-prompt ((t (:inherit (minibuffer-prompt)))))
   `(eshell-input ((t (:foreground ,accent-color))))
   `(eshell-ls-executable ((t (:foreground ,purple-1))))
   `(eshell-ls-directory ((t (:foreground ,blue-2))))
   `(eshell-ls-special ((t (:foreground ,orange-1))))
   `(eshell-ls-symlink ((t (:foreground ,green-1))))
   `(eshell-ls-readonly ((t (:foreground ,brown-1))))
   '(eshell-ls-unreadable ((t (:inherit (shadow)))))
   `(eshell-ls-missing ((t (:foreground ,error-color))))
   '(dired-flagged ((t (:strike-through t :inherit (error)))))
   `(dired-header ((t (:foreground ,accent-bg-color))))
   `(dired-mark ((t (:foreground ,accent-bg-color))))
   '(dired-marked ((t (:weight bold :inherit (font-lock-string-face)))))
   '(dired-perm-write ((t (:inherit (font-lock-function-name-face)))))
   '(dired-special ((t (:inherit (font-lock-keyword-face)))))
   '(dired-symlink ((t (:inherit (font-lock-variable-name-face)))))
   '(eshell-prompt ((t (:inherit (minibuffer-prompt)))))
   `(eshell-input ((t (:foreground ,accent-color))))
   '(eshell-ls-executable ((t (:inherit (font-lock-function-name-face)))))
   '(eshell-ls-directory ((t (:inherit (dired-directory)))))
   '(eshell-ls-special ((t (:inherit (dired-special)))))
   '(eshell-ls-symlink ((t (:inherit (dired-symlink)))))
   '(eshell-ls-readonly ((t (:inherit (font-lock-constant-face)))))
   '(eshell-ls-unreadable ((t (:inherit (shadow)))))
   '(eshell-ls-missing ((t (:inherit (dired-broken-symlink)))))
   '(eshell-syntax-highlighting-shell-command-face ((t (:inherit (eshell-ls-executable)))))
   '(eshell-syntax-highlighting-alias-face ((t (:inherit (font-lock-constant-face)))))
   '(eshell-syntax-highlighting-file-arg-face ((t (:inherit (eshell-ls-directory)))))
   '(eshell-syntax-highlighting-directory-face ((t (:inherit (eshell-ls-directory)))))
   '(git-annex-dired-annexed-available ((t (:inherit (dired-symlink)))))
   '(git-annex-dired-annexed-unavailable ((t (:inherit (dired-broken-symlink)))))
   '(org-block ((t (:inherit (fixed-pitch)))))
   '(org-code ((t (:inherit (fixed-pitch)))))
   '(term-color-black ((t (:foreground "#1A1821" :background "#1A1821"))))
   '(term-color-red ((t (:foreground "#FF8080" :background "#FF8080"))))
   '(term-color-green ((t (:foreground "#80FF80" :background "#80FF80"))))
   '(term-color-yellow ((t (:foreground "#FFFF80" :background "#FFFF80"))))
   '(term-color-blue ((t (:foreground "#8080FF" :background "#8080FF"))))
   '(term-color-magenta ((t (:foreground "#FF80FF" :background "#FF80FF"))))
   '(term-color-cyan ((t (:foreground "#80FFFF" :background "#80FFFF"))))
   '(term-color-white ((t (:foreground "#E7E4F2" :background "#E7E4F2"))))
   '(term-color-bright-black ((t (:foreground "#655D80" :background "#655D80"))))
   '(term-color-bright-red ((t (:foreground "#FF5050" :background "#FF5050"))))
   '(term-color-bright-green ((t (:foreground "#50FF50" :background "#50FF50"))))
   '(term-color-bright-yellow ((t (:foreground "#FFFF50" :background "#FFFF50"))))
   '(term-color-bright-blue ((t (:foreground "#5050FF" :background "#5050FF"))))
   '(term-color-bright-magenta ((t (:foreground "#FF50FF" :background "#FF50FF"))))
   '(term-color-bright-cyan ((t (:foreground "#50FFFF" :background "#50FFFF"))))
   '(term-color-bright-white ((t (:foreground "#FFFFFF" :background "#FFFFFF"))))
   '(ansi-color-black ((t (:inherit (term-color-black)))))
   '(ansi-color-red ((t (:inherit (term-color-red)))))
   '(ansi-color-green ((t (:inherit (term-color-green)))))
   '(ansi-color-yellow ((t (:inherit (term-color-yellow)))))
   '(ansi-color-blue ((t (:inherit (term-color-blue)))))
   '(ansi-color-magenta ((t (:inherit (term-color-magenta)))))
   '(ansi-color-cyan ((t (:inherit (term-color-cyan)))))
   '(ansi-color-white ((t (:inherit (term-color-white)))))
   '(ansi-color-bright-black ((t (:inherit (term-color-bright-black)))))
   '(ansi-color-bright-red ((t (:inherit (term-color-bright-red)))))
   '(ansi-color-bright-green ((t (:inherit (term-color-bright-green)))))
   '(ansi-color-bright-yellow ((t (:inherit (term-color-bright-yellow)))))
   '(ansi-color-bright-blue ((t (:inherit (term-color-bright-blue)))))
   '(ansi-color-bright-magenta ((t (:inherit (term-color-bright-magenta)))))
   '(ansi-color-bright-cyan ((t (:inherit (term-color-bright-cyan)))))
   '(ansi-color-bright-white ((t (:inherit (term-color-bright-white)))))
   '(vterm-color-black ((t (:foreground "#1A1821" :background "#655D80"))))
   '(vterm-color-red ((t (:foreground "#FF8080" :background "#FF0000"))))
   '(vterm-color-green ((t (:foreground "#80FF80" :background "#00FF00"))))
   '(vterm-color-yellow ((t (:foreground "#FFFF80" :background "#FFFF00"))))
   '(vterm-color-blue ((t (:foreground "#8080FF" :background "#0000FF"))))
   '(vterm-color-magenta ((t (:foreground "#FF80FF" :background "#FF00FF"))))
   '(vterm-color-cyan ((t (:foreground "#80FFFF" :background "#00FFFF"))))
   '(vterm-color-white ((t (:foreground "#E7E4F2" :background "#FFFFFF")))))

  (custom-theme-set-variables
   'adwaita
   '(rainbow-delimiters-max-face-count 6)
   '(orderless-match-faces [rainbow-delimiters-depth-1-face
                            rainbow-delimiters-depth-2-face
                            rainbow-delimiters-depth-3-face
                            rainbow-delimiters-depth-4-face
                            rainbow-delimiters-depth-5-face
                            rainbow-delimiters-depth-6-face])))

(provide-theme 'adwaita)

(provide 'adwaita-theme)
;;; adwaita-theme.el ends here
