#!/usr/bin/env bash
# Copyright (C) Archit Gupta <archit@accelbread.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

set -xu

export PATH=@path@

disksPart=(@devicesPart@)
name=@hostname@

umount /mnt/persist
umount /mnt/nix
umount /mnt/boot
umount /mnt

for i in $(seq 1 ${#disksPart[@]}); do
    vgchange -a n "${name}_vg${i}"
    cryptsetup close "${name}_disk${i}"
done
