{ pkgs, lib, ... }:
let
  use-ccache = false;
  stdenv = llvmStdenv pkgs.llvmPackages;
  base-kernel = pkgs.linux;

  llvmStdenv = llvmPackages:
    let inherit (llvmPackages) stdenv bintools; in
    pkgs.overrideCC stdenv (stdenv.cc.override { inherit bintools; });
in
{
  security.lsm = [ "lockdown" ];

  boot = {
    kernelPackages = pkgs.linuxPackagesFor (base-kernel.override (prev: {
      enableCommonConfig = false;
      extraMakeFlags = prev.extraMakeFlags or [ ] ++ [ "INSTALL_MOD_STRIP=1" ];
      inherit stdenv;
    } // lib.optionalAttrs use-ccache {
      stdenv = pkgs.ccacheStdenv.override { inherit stdenv; };
      buildPackages = pkgs.buildPackages // {
        stdenv = pkgs.buildPackages.ccacheStdenv;
      };
    }));
    kernelPatches = map (p: { name = baseNameOf p; patch = p; })
      (lib.filesystem.listFilesRecursive ./kernel-patches) ++
    lib.mapAttrsToList
      (k: v: { name = k; patch = null; structuredExtraConfig = v; })
      (with lib.kernel; {
        "base" = {
          ACPI_APEI_PCIEAER = yes;
          BINFMT_MISC = yes;
          BINFMT_SCRIPT = yes;
          BLK_DEV_INITRD = yes;
          BLK_DEV_NVME = module;
          BPF = yes;
          BPF_JIT = yes;
          BPF_SYSCALL = yes;
          CGROUPS = yes;
          CGROUP_BPF = yes;
          CGROUP_PIDS = yes;
          CRYPTO_CHACHA20POLY1305 = yes; # for kTLS
          DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT = yes;
          DEVTMPFS = yes;
          EPOLL = yes;
          FANOTIFY = yes;
          FUSE_FS = yes;
          FW_LOADER = yes;
          FW_LOADER_COMPRESS = yes;
          FW_LOADER_COMPRESS_ZSTD = yes;
          HAVE_EBPF_JIT = yes;
          HWMON = yes;
          I2C = yes;
          I2C_CHARDEV = module;
          INOTIFY_USER = yes;
          INPUT = yes;
          INPUT_KEYBOARD = yes;
          IPV6 = yes;
          IPV6_MULTIPLE_TABLES = yes;
          IP_MULTICAST = yes;
          IP_MULTIPLE_TABLES = yes;
          KCMP = yes;
          KERNEL_ZSTD = yes;
          LRU_GEN = yes;
          LRU_GEN_ENABLED = yes;
          MD = yes;
          MODULE_COMPRESS = yes;
          MODULE_COMPRESS_ALL = yes;
          MODULE_COMPRESS_ZSTD = yes;
          MPTCP = yes;
          MPTCP_IPV6 = yes;
          MQ_IOSCHED_DEADLINE = yes;
          NAMESPACES = yes;
          NETFILTER = yes;
          NETFILTER_ADVANCED = yes;
          NET_NS = yes;
          NET_SCHED = yes;
          NET_SCH_FQ_CODEL = yes;
          NF_TABLES_INET = yes;
          NF_TABLES_IPV4 = yes;
          NF_TABLES_IPV6 = yes;
          NVME_HWMON = yes;
          PCIEAER = yes;
          POSIX_MQUEUE = yes;
          PROC_FS = yes;
          RTC_HCTOSYS = yes;
          RT_GROUP_SCHED = no;
          SCHED_CORE = yes;
          SECCOMP = yes;
          SECCOMP_FILTER = yes;
          SECURITY = yes;
          SECURITY_LANDLOCK = yes;
          SIGNALFD = yes;
          SPI = yes;
          SYSFS = yes;
          SYSVIPC = yes;
          THERMAL = yes;
          THERMAL_HWMON = yes;
          TIMERFD = yes;
          TLS = yes;
          TMPFS = yes;
          TMPFS_POSIX_ACL = yes;
          TMPFS_XATTR = yes;
          TRANSPARENT_HUGEPAGE = yes;
          UNIX = yes;
          USER_NS = yes;
          WATCHDOG_SYSFS = yes;
        };
        "x86_64" = {
          ACPI = yes;
          ACPI_APEI = yes;
          ACPI_APEI_GHES = yes;
          HPET = no;
          IRQ_REMAP = yes;
          MICROCODE = yes;
          MTRR = yes;
          X86_MCE = yes;
          X86_PAT = yes;
          X86_USER_SHADOW_STACK = yes;
          X86_X2APIC = yes;
        };
        "performance" = {
          BLK_WBT = yes;
          BLK_WBT_MQ = yes;
          CPU_FREQ_DEFAULT_GOV_SCHEDUTIL = yes;
          DEFAULT_BBR = yes;
          NO_HZ_IDLE = yes;
          PREEMPT = yes;
          PREEMPT_DYNAMIC = no;
          RCU_EXPERT = yes;
          RCU_LAZY = yes;
          RCU_NOCB_CPU = yes;
          READ_ONLY_THP_FOR_FS = yes;
          SCHED_AUTOGROUP = yes;
          TCP_CONG_BBR = yes;
          THERMAL_DEFAULT_GOV_STEP_WISE = yes;
          TRANSPARENT_HUGEPAGE_ALWAYS = yes;
          X86_64_VERSION = freeform "3";
          ZSWAP = yes;
          ZSWAP_COMPRESSOR_DEFAULT_ZSTD = yes;
        };
        "monitoring" = {
          IRQ_TIME_ACCOUNTING = yes;
          TASKSTATS = yes;
          TASK_IO_ACCOUNTING = yes;
          TASK_XACCT = yes;
        };
        "systemd" = {
          AUTOFS_FS = yes;
          BLK_CGROUP_IOCOST = yes;
          BPF_LSM = yes;
          CFS_BANDWIDTH = yes;
          CGROUP_SCHED = yes;
          DEBUG_INFO_BTF = yes;
          DMIID = yes;
          FAIR_GROUP_SCHED = yes;
          FHANDLE = yes;
          FW_LOADER_USER_HELPER = no;
          MEMCG = yes;
          PSI = yes;
          UEVENT_HELPER = no;
        };
        "uefi" = {
          EFI = yes;
          EFIVAR_FS = yes;
          EFI_PARTITION = yes;
          EFI_STUB = yes;
          EFI_VARS_PSTORE = yes;
          NLS_CODEPAGE_437 = module;
          NLS_ISO8859_1 = module;
          VFAT_FS = module;
        };
        "dm-crypt" = {
          CRYPTO_AES = yes;
          CRYPTO_SHA256 = yes;
          CRYPTO_SHA512 = yes;
          CRYPTO_XTS = yes;
        };
        "filesystem" = {
          BTRFS_FS = yes;
          BTRFS_FS_POSIX_ACL = yes;
          FS_VERITY = yes;
        };
        "display" = {
          BACKLIGHT_CLASS_DEVICE = yes;
          DRM = yes;
          DRM_FBDEV_EMULATION = yes;
          DRM_PANIC = yes;
          DRM_PANIC_SCREEN = freeform "kmsg";
          DRM_SIMPLEDRM = yes;
          FB = no;
          FONTS = yes;
          FONT_8x16 = yes;
          FONT_TER16x32 = yes;
          FRAMEBUFFER_CONSOLE = yes;
          FRAMEBUFFER_CONSOLE_DETECT_PRIMARY = yes;
          SYSFB_SIMPLEFB = yes;
        };
        "audio" = {
          SND = module;
          SND_DYNAMIC_MINORS = yes;
          SND_HDA_CODEC_HDMI = module;
          SND_HDA_INPUT_BEEP = yes;
          SND_HDA_INTEL = module;
          SND_HDA_POWER_SAVE_DEFAULT = freeform "10";
          SND_USB_AUDIO = module;
          SOUND = module;
        };
        "usb" = {
          USB = yes;
          USB_HIDDEV = yes;
          USB_SERIAL = yes;
          USB_STORAGE = module;
          USB_UAS = module;
          USB_XHCI_HCD = module;
        };
        "hid" = {
          HIDRAW = yes;
          HID_BATTERY_STRENGTH = yes;
          HID_GENERIC = module;
          HID_HAPTIC = yes;
        };
        "wireless" = {
          BT_HCIBTUSB_AUTOSUSPEND = yes;
          CFG80211 = module;
          MAC80211 = module;
          RFKILL_INPUT = yes;
        };
        "amdgpu" = {
          DEVICE_PRIVATE = yes;
          DMABUF_MOVE_NOTIFY = yes;
          DRM_AMD_DC = yes;
          HSA_AMD = yes;
          HSA_AMD_P2P = yes;
          HSA_AMD_SVM = yes;
          MEMORY_HOTPLUG = yes;
          MEMORY_HOTREMOVE = yes;
          PCI_P2PDMA = yes;
          ZONE_DEVICE = yes;
        };
        "VMs" = {
          UDMABUF = yes;
        };
        "misc" = {
          IKCONFIG = yes;
          IKCONFIG_PROC = yes;
          KEXEC_FILE = yes;
          SCHED_CLASS_EXT = yes;
        };
        "debug" = {
          DETECT_HUNG_TASK = yes;
          DYNAMIC_DEBUG = yes;
          HARDLOCKUP_DETECTOR = yes;
          LOCKUP_DETECTOR = yes;
          SOFTLOCKUP_DETECTOR = yes;
        };
        "hardening" = {
          AIO = no;
          AMD_IOMMU = yes;
          AUDIT = yes;
          BLK_DEV_WRITE_MOUNTED = no;
          BPF_JIT_ALWAYS_ON = yes;
          BUG = yes;
          BUG_ON_DATA_CORRUPTION = yes;
          COMPAT_BRK = no;
          COMPAT_VDSO = no;
          CRYPTO_USER_API = option no;
          CRYPTO_USER_API_AEAD = no;
          CRYPTO_USER_API_HASH = no;
          CRYPTO_USER_API_RNG = no;
          CRYPTO_USER_API_SKCIPHER = no;
          DEBUG_FS = no;
          DEBUG_LIST = yes;
          DEBUG_NOTIFIERS = yes;
          DEBUG_PLIST = yes;
          DEBUG_SG = yes;
          DEBUG_VIRTUAL = yes;
          DEBUG_WX = yes;
          DEVMEM = no;
          DEVPORT = no;
          EFI_DISABLE_PCI_DMA = yes;
          EXPERT = yes;
          FORTIFY_SOURCE = yes;
          HARDENED_USERCOPY = yes;
          HARDENED_USERCOPY_DEFAULT_ON = yes;
          HW_RANDOM = yes;
          HW_RANDOM_TPM = yes;
          INET_DIAG = no;
          INIT_ON_ALLOC_DEFAULT_ON = yes;
          INIT_ON_FREE_DEFAULT_ON = yes;
          INIT_STACK_ALL_ZERO = yes;
          INTEL_IOMMU = yes;
          INTEL_IOMMU_DEFAULT_ON = yes;
          INTEL_IOMMU_SVM = yes;
          IOMMU_DEFAULT_DMA_STRICT = yes;
          IOMMU_DEFAULT_PASSTHROUGH = no;
          IOMMU_SUPPORT = yes;
          KEXEC = no;
          KEXEC_SIG = yes;
          KEXEC_SIG_FORCE = yes;
          KFENCE = yes;
          KSTACK_ERASE = yes;
          LDISC_AUTOLOAD = no;
          LEGACY_PTYS = no;
          LEGACY_TIOCSTI = no;
          LEGACY_VSYSCALL_NONE = yes;
          LIST_HARDENED = yes;
          LOCK_DOWN_KERNEL_FORCE_INTEGRITY = yes;
          MITIGATION_PAGE_TABLE_ISOLATION = yes;
          MITIGATION_SLS = yes;
          MODIFY_LDT_SYSCALL = no;
          MODULE_HASHES = yes;
          MODULE_SIG = no;
          MODULE_SIG_FORCE = yes;
          MSEAL_SYSTEM_MAPPINGS = yes;
          NFS_DEBUG = unset;
          PAGE_TABLE_CHECK = yes;
          PAGE_TABLE_CHECK_ENFORCED = yes;
          PANIC_ON_OOPS = yes;
          PANIC_TIMEOUT = freeform "-1";
          PROC_KCORE = no;
          PROC_MEM_NO_FORCE = yes;
          PROC_VMCORE = no;
          RANDOMIZE_BASE = yes;
          RANDOMIZE_KSTACK_OFFSET_DEFAULT = yes;
          RANDOMIZE_MEMORY = yes;
          RANDOM_KMALLOC_CACHES = yes;
          RESET_ATTACK_MITIGATION = yes;
          SCHED_STACK_END_CHECK = yes;
          SECURITY_DMESG_RESTRICT = yes;
          SECURITY_LOCKDOWN_LSM = yes;
          SECURITY_LOCKDOWN_LSM_EARLY = yes;
          SECURITY_YAMA = yes;
          SHUFFLE_PAGE_ALLOCATOR = yes;
          SLAB_BUCKETS = yes;
          SLAB_FREELIST_HARDENED = yes;
          SLAB_FREELIST_RANDOM = yes;
          SLAB_MERGE_DEFAULT = no;
          SLUB_DEBUG = yes;
          STACKPROTECTOR = yes;
          STACKPROTECTOR_STRONG = yes;
          STRICT_KERNEL_RWX = yes;
          STRICT_MODULE_RWX = yes;
          SYN_COOKIES = yes;
          TCG_TPM = yes;
          UBSAN = yes;
          UBSAN_ALIGNMENT = option no;
          UBSAN_BOOL = option no;
          UBSAN_BOUNDS = yes;
          UBSAN_DIV_ZERO = option no;
          UBSAN_ENUM = option no;
          UBSAN_INTEGER_WRAP = option no;
          UBSAN_SHIFT = option no;
          UBSAN_TRAP = yes;
          UBSAN_UNREACHABLE = option no;
          UID16 = no;
          USERFAULTFD = no;
          VMAP_STACK = yes;
          X86_16BIT = unset;
          X86_INTEL_TSX_MODE_OFF = yes;
          X86_IOPL_IOPERM = no;
          X86_KERNEL_IBT = yes;
          ZERO_CALL_USED_REGS = yes;
        } // lib.optionalAttrs (!stdenv.cc.isClang) {
          GCC_PLUGINS = yes;
          GCC_PLUGIN_STACKLEAK = yes;
        } // lib.optionalAttrs stdenv.cc.isClang {
          CFI = yes;
          CFI_PERMISSIVE = no;
          FINEIBT = no;
        };
        "linux-hardened config" = {
          OVERLAY_FS_UNPRIVILEGED = yes;
          SLAB_CANARY = no;
          USER_NS_UNPRIVILEGED = yes;
        };
        "shadowfang hardware" = {
          ACPI_DPTF = yes;
          ACPI_EC = yes;
          CHROME_PLATFORMS = yes;
          CROS_EC = module;
          CROS_EC_LPC = module;
          CROS_KBD_LED_BACKLIGHT = module;
          DRM_I915 = module;
          HID_MULTITOUCH = module;
          HID_SENSOR_ALS = module;
          HOTPLUG_PCI_PCIE = yes;
          I2C_DESIGNWARE_CORE = module;
          I2C_DESIGNWARE_PLATFORM = module;
          I2C_HID = module;
          I2C_HID_ACPI = module;
          I2C_I801 = module;
          IIO = module;
          INT340X_THERMAL = module;
          INTEL_HFI_THERMAL = yes; # used by intel-lpmd
          INTEL_IDLE = yes;
          INTEL_PMC_CORE = module;
          INTEL_RAPL = module;
          KEYBOARD_ATKBD = module;
          MFD_INTEL_LPSS_PCI = module;
          MFD_INTEL_PMC_BXT = module;
          SND_SOC_SOF_HDA_AUDIO_CODEC = yes;
          SND_SOC_SOF_HDA_LINK = yes;
          SND_SOC_SOF_INTEL_TOPLEVEL = yes;
          SND_SOC_SOF_PCI = module;
          SND_SOC_SOF_TOPLEVEL = yes;
          TCG_TIS = yes;
          THERMAL_GOV_USER_SPACE = yes; # used by thermald
          TYPEC_DP_ALTMODE = module;
          TYPEC_TBT_ALTMODE = module;
          TYPEC_UCSI = module;
          USB4 = module;
          X86_INTEL_LPSS = yes;
          X86_INTEL_PSTATE = yes;
          X86_PKG_TEMP_THERMAL = module;
          # TCG_CRB = yes; # will be needed for fw pro
        };
        "solace hardware" = {
          CRYPTO_DEV_CCP = yes;
          MEMORY_FAILURE = yes;
          PERF_EVENTS_AMD_BRS = yes;
          PINCTRL_AMD = yes;
          SENSORS_IT87 = module;
          TCG_TIS = yes;
          X86_AMD_PLATFORM_DEVICE = yes;
          X86_AMD_PSTATE = yes;
        };
        "peripherals" = {
          INPUT_JOYSTICK = yes;
          MEDIA_CAMERA_SUPPORT = yes;
          MEDIA_USB_SUPPORT = yes;
          NINTENDO_FF = yes;
          PLAYSTATION_FF = yes;
        };
        "Disable vulernable kernel modules" = {
          AF_RXRPC = no;
          INET6_ESP = no;
          INET_ESP = no;
          RDS = no;
        };
        "defconfig junk" = {
          "8139TOO_PIO" = no;
          ACERHDF = no;
          ADFS_FS = no;
          AFFS_FS = no;
          AGP = no;
          AIC79XX_DEBUG_ENABLE = no;
          AIC7XXX_DEBUG_ENABLE = no;
          AIC94XX_DEBUG = no;
          BEFS_FS = no;
          BFS_FS = no;
          BLK_DEV_IO_TRACE = no;
          BSD_PROCESS_ACCT = no;
          CRAMFS = no;
          DEBUG_DEVRES = no;
          DEBUG_STACK_USAGE = no;
          DVB_CORE = no;
          ECRYPT_FS = no;
          EDAC_IGEN6 = no;
          EFI_TEST = no;
          EFS_FS = no;
          EROFS_FS = no;
          EXFAT_FS = no;
          EXT2_FS = no;
          EXT4_FS = no;
          F2FS_FS = no;
          GFS2_FS = no;
          GLOB_SELFTEST = no;
          GPIO_VIRTUSER = no;
          HFSPLUS_FS = no;
          HFS_FS = no;
          HPFS_FS = no;
          HYPERVISOR_GUEST = no;
          IP_MROUTE = no;
          IP_PNP = no;
          IP_VS = no;
          ISO9660_FS = no;
          JFFS2_FS = no;
          JFS_FS = no;
          KUNIT = no;
          L2TP = no;
          LOCK_TORTURE_TEST = no;
          LOGO = no;
          MINIX_FS = no;
          MSDOS_FS = no;
          MTD_TESTS = no;
          NETWORK_FILESYSTEMS = no;
          NILFS2_FS = no;
          NOTIFIER_ERROR_INJECTION = no;
          NTFS_FS = no;
          NUMA = no;
          OCFS2_FS = no;
          OMFS_FS = no;
          ORANGEFS_FS = no;
          PCMCIA = no;
          PPP = no;
          PUNIT_ATOM_DEBUG = no;
          QNX4FS_FS = no;
          QNX6FS_FS = no;
          RCU_SCALE_TEST = no;
          RCU_TORTURE_TEST = no;
          RING_BUFFER_BENCHMARK = no;
          ROMFS_FS = no;
          RUNTIME_TESTING_MENU = no;
          SQUASHFS = no;
          TEST_ASYNC_DRIVER_PROBE = no;
          UBIFS_FS = no;
          UDF_FS = no;
          UFS_FS = no;
          VXFS_FS = no;
          WERROR = no;
          WW_MUTEX_SELFTEST = no;
          XFS_FS = no;
          XZ_DEC_TEST = no;
        };
      });

    kernelParams = [
      "lockdown_hibernate"
      "init_on_alloc=1"
      "init_on_free=1"
      "iommu.passthrough=0"
      "iommu.strict=1"
      "iommu=force"
      "intel_iommu=on"
      "amd_iommu=force_isolation"
      "randomize_kstack_offset=on"
      "page_alloc.shuffle=1"
      "slab_nomerge"
      "pti=on"
      "mce=0"
      "random.trust_bootloader=off"
      "random.trust_cpu=off"
      "proc_mem.force_override=never"
      "hash_pointers=always"
      "slub_debug=ZF"
      "zswap.enabled=1"
      "zswap.shrinker_enabled=1"
      "vsyscall=none"
      "vdso32=0"
    ];

    kernel.sysctl = {
      "dev.tty.ldisc_autoload" = 0;
      "dev.tty.legacy_tiocsti" = false;
      "fs.protected_symlinks" = 1;
      "fs.protected_hardlinks" = 1;
      "fs.protected_fifos" = 2;
      "fs.protected_regular" = 2;
      "fs.suid_dumpable" = 0;
      "kernel.dmesg_restrict" = true;
      "kernel.ftrace_enabled" = false;
      "kernel.io_uring_disabled" = 2;
      "kernel.kexec_load_disabled" = true;
      "kernel.kptr_restrict" = 2;
      "kernel.perf_event_paranoid" = 3;
      "kernel.sysrq" = 0;
      "kernel.unprivileged_bpf_disabled" = 1;
      "kernel.yama.ptrace_scope" = 1;
      "net.core.bpf_jit_harden" = 2;
      "net.core.rmem_max" = 5000000;
      "net.core.wmem_max" = 5000000;
      "net.ipv4.conf.all.accept_redirects" = false;
      "net.ipv4.conf.all.rp_filter" = 2;
      "net.ipv4.conf.all.secure_redirects" = false;
      "net.ipv4.conf.all.send_redirects" = false;
      "net.ipv4.conf.default.accept_redirects" = false;
      "net.ipv4.conf.default.rp_filter" = 2;
      "net.ipv4.conf.default.secure_redirects" = false;
      "net.ipv4.conf.default.send_redirects" = false;
      "net.ipv4.tcp_congestion_control" = "bbr";
      "net.ipv4.tcp_thin_linear_timeouts" = 1;
      "net.ipv6.conf.all.accept_redirects" = false;
      "net.ipv6.conf.all.use_tempaddr" = 2;
      "net.ipv6.conf.default.accept_redirects" = false;
    };

    initrd.systemd.contents."/etc/lvm/lvm.conf".text = lib.mkAfter ''
      global/use_aio = 0
    '';
  };

  environment.etc."lvm/lvm.conf".text = lib.mkAfter ''
    global/use_aio = 0
  '';
}
