substitutions:
  light_restore_mode: ALWAYS_ON
packages:
  Kauf.RGBWW:
    url: https://github.com/KaufHA/kauf-rgbww-bulbs
    files:
      - kauf-bulb.yaml
    ref: 758f86c00de7ba2a5e1626ad2fccb2bd71ec2a82
esphome:
  name: ${name}
  name_add_mac_suffix: false
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
mqtt:
  broker: !secret mqtt_broker
  discovery: false
  topic_prefix: home/bulb/${name}
  reboot_timeout: 0s
  keepalive: 60s
