substitutions:
  light_restore_mode: ALWAYS_ON
packages:
  Kauf.RGBWW: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
mqtt:
  broker: !secret mqtt_broker
  discovery: false
  topic_prefix: home/bulb/${name}
  reboot_timeout: 0s
  keepalive: 60s
