monitor.bluez.rules = [
  {
    matches = [
      { node.name = "bluez_output.58_18_62_1E_D8_3B.1" }
    ]
    actions = {
      update-props = {
        priority.session = 1020
      }
    }
  }
  {
    matches = [
      { node.name = "bluez_input.58_18_62_1E_D8_3B.0" }
    ]
    actions = {
      update-props = {
        priority.session = 2020
      }
    }
  }
]
