monitor.alsa.rules = [
  {
    matches = [
      { node.name = "alsa_output.usb-XREAL_XREAL_One-05.analog-stereo" }
    ]
    actions = {
      update-props = {
        priority.session = 1010
      }
    }
  }
  {
    matches = [
      { node.name = "alsa_input.usb-XREAL_XREAL_One-05.analog-stereo" }
    ]
    actions = {
      update-props = {
        priority.session = 2010
      }
    }
  }
]
