#!/usr/bin/env bash
set -euo pipefail

sopin=$(head -c 15 /dev/urandom | base64)
tpm2_ptool init
tpm2_ptool addtoken --pid=1 --label=nix-ssh --userpin= --sopin="$sopin"
tpm2_ptool addkey --label=nix-ssh --userpin= --algorithm=ecc256

echo Public key:
ssh-keygen -D /run/current-system/sw/lib/libtpm2_pkcs11.so
