monitor.alsa.rules = [
  {
    matches = [
      { device.name = "alsa_card.usb-Elgato_Systems_Elgato_Wave_XLR_DS16M2A00891-00" }
    ]
    actions = {
      update-props = {
        device.profile = "input:mono-fallback"
        device.routes.default-source-volume = 0.005
      }
    }
  }
  {
    matches = [
      { node.name = "alsa_input.usb-Elgato_Systems_Elgato_Wave_XLR_DS16M2A00891-00.mono-fallback" }
    ]
    actions = {
      update-props = {
        priority.session = 2100
      }
    }
  }
]
