wireplumber.components = [
  {
    name = "mute-input-routes.lua"
    type = script/lua
    provides = custom.mute-input-routes
  }
]
wireplumber.profiles = {
  main = {
    custom.mute-input-routes = required
  }
}
