monitor.bluez.rules = [
  {
    matches = [
      { node.name = "bluez_output.88_C9_E8_1F_5A_99.1" }
    ]
    actions = {
      update-props = {
        priority.session = 1020
      }
    }
  }
  {
    matches = [
      { node.name = "bluez_input.88_C9_E8_1F_5A_99.0" }
    ]
    actions = {
      update-props = {
        priority.session = 2020
      }
    }
  }
]
