substitutions:
  name: kauf-bulb-7d02ed
  light_restore_mode: ALWAYS_ON
packages:
  Kauf.RGBWW:
    url: https://github.com/KaufHA/kauf-rgbww-bulbs
    files:
      - kauf-bulb.yaml
    ref: b82721c483f80e4ad07338615e95022b2a5ac28a
esphome:
  name: ${name}
  name_add_mac_suffix: false
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
