[formatter.c]
command = "clang-format"
options = ["-i"]
includes = ["*.c", "*.h"]

[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.md"]
