[formatter.rust]
command = "rustfmt"
includes = ["*.rs"]

[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.md"]
